config/routes.rb
Rails.application.routes.draw do
  resources :contact_logs, only: [:index]
  # resources :contacts, only: [:show]
  resources :contact_files, except: [:update, :destroy, :edit]
  devise_for :users
  root 'contacts#index'

  if defined?(Sidekiq) && defined?(Sidekiq::Web)
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  after_create :set_franchise

  validates :name, presence: true, format: { with: /-*\w+-*\w+-*/ }
  validates :date_of_birth, presence: true, format: { with: /\d{4}-?\d{2}-?\d{2}/}
  validates :phone, presence: true, format: { with: /(\({1}\+{1}\d{2}\){1})\s?-?(\d{3})\s?-?(\d{3})\s?-?(\d{2})\s?-?(\d{2})/}
  validates :address, presence: true
  validates :credit_card, presence: true, credit_card_number: true
  validates :email, uniqueness: { scope: :user_id}

  encrypts :credit_card

  def get_credit_card
    number = self.credit_card
    digits = number.length
    number[0..digits-5] = "**** **** "
    number
  end

  private

  def set_franchise
    detector = CreditCardValidations::Detector.new(credit_card)
    self.update(franchise: detector.brand.to_s)
  end
end

app/models/contact_file.rb
class ContactFile < ApplicationRecord
  belongs_to :user

  after_create_commit :generate_contacts
  
  has_one_attached :csv

  private
  
  def generate_contacts
    self.update(status: "On Hold")
    ImportContactJob.perform_later(id)

  end
end

app/models/contact_log.rb
class ContactLog < ApplicationRecord
  belongs_to :user

  validates :elements, presence: true
  validates :error, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :contact_files
  has_many :contacts
  has_many :contact_logs

  validates :email, presence: true
  validates :password, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found
  
  private

  def resource_not_found
    respond_to do |format|
      format.html{ render template: '/contact_files/index', status: 404 }
    end
  end
end

app/controllers/contact_files_controller.rb
class ContactFilesController < ApplicationController
  before_action :authenticate_user!

  before_action :assign_contact_file, only: [:show]

  respond_to :html

  def index
    @contact_files = current_user.contact_files.page params[:page]
  end

  def show; end

  def new
    @contact_file = current_user.contact_files.new
  end

  def create
    @contact_file = current_user.contact_files.create(contact_file_params)
    flash[:notice] = 'Contact file was successfully created.' if @contact_file.save
    redirect_to contact_files_path

  end

  private

  def assign_contact_file
    @contact_file = ContactFile.find(params[:id])
  end

  def contact_file_params
    params.require(:contact_file).permit(:alias_name, :alias_email, :alias_phone,
                                         :alias_address, :alias_date_of_birth,
                                         :alias_credit_card, :csv)
  end
end

app/controllers/contact_logs_controller.rb
class ContactLogsController < ApplicationController
  before_action :authenticate_user!
  def index
    @contact_logs = current_user.contact_logs.page params[:page]
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  # before_action :assign_contact, only: [:show]

  # def show
  # end

  def index
    @contacts = current_user.contacts.page params[:page]
  end

  # private

  # def assign_contact
  #   @contact = ContactFile.find(params[:id])
  # end
end

app/helpers/contact_file_helper.rb
module ContactFileHelper
end

app/helpers/contact_logs_helper.rb
module ContactLogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contact_files/_contact_file.html.erb
<tr>
  <td><%= contact_file.csv.filename %></td>
  <th><%= contact_file.status %></th>
  <th><%= contact_file.created_at %></th>
</tr>

app/views/contact_files/_form.html.erb
<h1>Import contact forms</h1>

  <p>Write the alias that each field receives in your contact file, the fields that do not 
  change do not edit them, please.</p>
<%= form_for [@contact_file] do |form| %>
  <% if @contact_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_file.errors.count, "error") %> prohibited this contact_file from being saved:</h2>

      <ul>
        <% contact_file.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :alias_name,"The alias for the name in your contacts file", class: "form-label" %>
    <%= form.text_field :alias_name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :alias_date_of_birth,"The alias for the date of birth in your contacts file", class: "form-label" %>
    <%= form.text_field :alias_date_of_birth, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :alias_phone,"The alias for the phone number in your contacts file", class: "form-label" %>
    <%= form.text_field :alias_phone, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :alias_address,"The alias for the address in your contacts file", class: "form-label" %>
    <%= form.text_field :alias_address, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :alias_credit_card,"The alias for the credit card number in your contacts file", class: "form-label" %>
    <%= form.text_field :alias_credit_card, class: "form-control" %>
  </div>
  
  <div class="mb-3">
    <%= form.label :alias_email,"The alias for the email in your contacts file", class: "form-label" %>
    <%= form.text_field :alias_email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :csv,"Upload you csv file" %>
    <%= form.file_field :csv, class: "form-control-file" %>
    <div class="form-text">The credti card numbers will be encrypted.</div>
  </div>
  
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
<br>
<%= link_to "Contact files", contact_files_path, class: "btn btn-primary"%>
<%= link_to "Contacts", root_path, class: "btn btn-primary"%>

app/views/contact_files/index.html.erb
<h1>Contact files</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">File name</th>
      <th scope="col">Status</th>
      <th scope="col">Upload date</th>
    </tr>
  </thead>
  <tbody>
    <%= render @contact_files unless @contact_files.nil? %>
  </tbody>
</table>
<%= paginate @contact_files %>

<%= link_to "Import contacts", new_contact_file_path, class: "btn btn-primary"%>
<%= link_to "See contacts", root_path, class: "btn btn-primary"%>

app/views/contact_files/new.html.erb
<%= render "form", request: @contact_file %>

app/views/contact_files/show.html.erb
<h1>Hola#show</h1>

app/views/contact_logs/_contact_log.html.erb
<tr>
  <td><%= contact_log.elements %></td>
  <td><%= contact_log.error %></td>
  <td><%= contact_log.created_at.strftime("%Y %B %d") %></td>
</tr>

app/views/contact_logs/index.html.erb
<h1>Contact Logs</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Elements</th>
      <th scope="col">Error</th>
      <th scope="col">Upload date</th>
    </tr>
  </thead>
  <tbody>
    <%= render @contact_logs unless @contact_logs.nil? %>
  </tbody>
</table>
<%= paginate @contact_logs %>

<%= link_to "Contacts", root_path, class: "btn btn-primary"%>

app/views/contacts/_contact.html.erb
<tr>
  <th scope="row"><%= contact.name %></th>
  <td><%= contact.date_of_birth.strftime("%Y %B %d") %></td>
  <td><%= contact.phone %></td>
  <td><%= contact.address %></td>
  <td><%= contact.get_credit_card %></td>
  <td><%= contact.franchise %></td>
  <td><%= contact.email %></td>
</tr>

app/views/contacts/index.html.erb
<h1>Contacts</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Daet of birth</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col">Credit Card</th>
      <th scope="col">Franchise</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
    <%= render @contacts unless @contacts.nil? %>
  </tbody>
</table>
<%= paginate @contacts %>
<br>
<span>Import more contacts</span>
<br>
<div>
  <%= link_to "Import contacts", new_contact_file_path, class: "btn btn-primary"%>
</div>
<br>
<span>See imported files</span>
<br>
<div>
  <%= link_to "Contact files", contact_files_path, class: "btn btn-primary"%>
</div>
<br>
<span>See faile imported contacts</span>
<br>
<div>
  <%= link_to "Filed contacts", contact_logs_path, class: "btn btn-primary"%>
</div>

app/views/contacts/show.html.erb
<h1>Contacts#show</h1>
<p>Find me in app/views/contacts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "shared/nav" %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
  <ul class="nav justify-content-end">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Log-out", destroy_user_session_path, method: :delete, class: "nav-link active" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log-in", new_user_session_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign-up", new_user_registration_path, class: "nav-link active" %>
        </li>
      <% end %>
    </ul>